image: "python:3.6"

before_script:
  - pip install -r requirements.txt
  - pip install pycrypto

stages:
  - Static Analysis

flake8:
  stage: Static Analysis
  script:
  - flake8 --max-line-length=120

